print("Calculate the Pythagorean Therom.")
asquared = float(input("Enter the first side's length: "))
bsquared = float(input("Enter the  second side's length: "))
csquared = (asquared*asquared+bsquared*bsquared)
print(f"The answer is {csquared}")